apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
data:
  username: # put your base64 encoded username here (no quotes)
  password: # put your base64 encoded password here (no quotes)

  # Base64 encode your username and password here:  https://www.base64encode.org